### ISSUE TITLE
Add some examples (with screenshots) to the documentation

### ISSUE THREAD

**Issue by Pipeliner** [casfeq/TrussFELib#1]
Hello and thank you for this project!

Could you please provide an example or two (with screenshots) of what this program is capable of?
I'm currently researching truss modelling applications and can't decide whether it suits my needs based on current README. And the building process seems quite complicated since it involves building PETSc...

(Specifically, I'm interested in looking what happens to a truss with many degrees of freedom when you drag some node a little. All elements are supposed to be rigid, I only want to obtain displacements).

**Comment by casfeq** [comment]
Hello!

This is a very simple program for simple truss problems. I've made it out of another program so it's kind of a Frankenstein code (that's the main reason I used PETSc).

I added an example to the README. Could you check if it clarifies your questions?

Thank you!

**Comment by Pipeliner** [comment]
Thank you, that's a great example with awesome illustrations!
